# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
import dataclasses
import uuid


@dataclasses.dataclass()
class Channel:
    id: int
    channel: str
    title: str
    default: bool


@dataclasses.dataclass()
class User:
    id: uuid.UUID
    username: str
    given_name: str
    family_name: str
    enabled: bool


@dataclasses.dataclass()
class UserChannel:
    user_id: uuid.UUID
    chan_id: int
    can_publish: bool
